### PR TITLE
Using pyserial library instead of pty on Windows OS

### PR DESCRIPTION
**Pull request by qqj1228**
pty can‘t working on windows system, so I changed it into pyserial. And you should install virtual serial port software(such as com0com) first.
And change some code in function handle in elm.py, it can improved a little efficiency

### CODE REVIEW

**Comment by Ircama** [comment]
Thanks, I'll revise your code and perform testing in the next days.
From a first look, I would suggest splitting different topics into separate pull requests.
It would be also useful squashing the various commits into a single one.

**Comment by Ircama** [comment]
OK, I'll merge your modifications and add some edits later. Thanks!

**Comment by qqj1228** [comment]
That‘s all right.
I find the OBD response message in obd_message.py only support CAN protocol，Maybe I’ll do some job to let it support K Line protocol in the next few days

**Comment by Ircama** [comment]
OK thanks.
I would suggest that, to simplify revision of your contributions, you coluld keep your master up-to-date with upstream. Then please create a new branch, do there your changes and commits. When issuing a pull request, please squash your commits first into a single one.

**Comment by qqj1228** [comment]
OK

**Pull request merged**
